---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: pkis.cluster.kubeception.ulfo.fr
spec:
  group: cluster.kubeception.ulfo.fr
  names:
    kind: Pki
    listKind: PkiList
    plural: pkis
    singular: pki
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Pki is the Schema for the pkis API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PkiSpec defines the desired state of Pki
            properties:
              admin:
                properties:
                  name:
                    type: string
                type: object
              ca:
                properties:
                  name:
                    type: string
                type: object
              controlplane-ips:
                type: string
              konnectivity:
                properties:
                  name:
                    type: string
                type: object
              kube-apiserver:
                properties:
                  DNSNames:
                    items:
                      type: string
                    type: array
                  IPAddresses:
                    items:
                      type: string
                    type: array
                  name:
                    type: string
                type: object
              kube-controller-manager:
                properties:
                  name:
                    type: string
                type: object
              kube-scheduler:
                properties:
                  name:
                    type: string
                type: object
              name:
                type: string
              service-accounts:
                properties:
                  name:
                    type: string
                type: object
            type: object
          status:
            description: PkiStatus defines the observed state of Pki
            properties:
              ready:
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
